security:
    encoders:
        RideChicago\AutoBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: RideChicago\AutoBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern:  login_path
            security: false
            anonymous:  ~

        secured_area:
            pattern:    ^/admin(/|/*)
            form_login:
                success_handler: authentication_handler
                failure_handler: authentication_handler
                check_path: login_check_path

            logout:
                path:   logout_path
                target: login_path
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /admin(/|/*), roles: ROLE_ADMIN }
        - { path: login_path, roles: IS_AUTHENTICATED_ANONYMOUSLY}
