ride_chicago_auto_homepage:
    pattern:  /
    defaults: { _controller: RideChicagoAutoBundle:Default:index }
    
auto_admin_index:
    pattern:  /admin/
    defaults: { _controller: RideChicagoAutoBundle:Admin\Index:index }
    
auto_admin_login:
    pattern:  /login
    defaults: { _controller: RideChicagoAutoBundle:Admin\Login:index }
    
auto_admin_users_view:
    pattern:  /admin/users
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userView }
    
auto_admin_users_add:
    pattern:  /admin/users/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userAdd }  
        
auto_admin_users_update:
    pattern:  /admin/users/edit/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userUpdate }  
    
auto_admin_classes_view:
    pattern:  /admin/classes
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classView }
        
auto_admin_classes_add:
    pattern:  /admin/classes/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classAdd }
        
auto_admin_classestypes_view:
    pattern:  /admin/class-types
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesView }
        
auto_admin_classestypes_add:
    pattern:  /admin/class-types/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesAdd }
         
auto_admin_classestypes_update:
    pattern:  /admin/class-types/edit/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesEdit }
    
auto_admin_registration:
    pattern:  /admin/registration
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationView }   
    
auto_admin_registration_add:
    pattern:  /admin/registration/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationAdd }

# API routes    

navigation:
  pattern: /api/navigation
  defaults: {_controller: RideChicagoAutoBundle:Services\Navigation:index, _format: json}
  
users_get:
  pattern: /api/users
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json} 
    
users_get_single:
  pattern: /api/users/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json} 
  requirements:
    id: \d+
  
users_create:
  pattern: /api/users/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:create, _format: json}    
  methods: [POST]  
  
users_update:
  pattern: /api/users/update
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:update, _format: json}    
  methods: [POST]  
  
users_delete:
  pattern: /api/users/delete
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:delete, _format: json}    
  methods: [POST]
  
classtypes_get:
  pattern: /api/class-types
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:get, _format: json}    
  
classtypes_get_single:
  pattern: /api/class-types/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:get, _format: json}    
  requirements:
    id: \d+
  
classtypes_reorder:
  pattern: /api/class-types/reorder
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:reorder, _format: json}    
  methods: [POST]  
  
classtypes_create:
  pattern: /api/class-types/create
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:create, _format: json}    
  methods: [POST]
  
classtypes_update:
  pattern: /api/class-types/update
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:update, _format: json}    
  methods: [POST]
  
classtypes_delete:
  pattern: /api/class-types/delete
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:delete, _format: json}    
  methods: [POST]

classrooms_get:
  pattern: /api/classes
  defaults: {_controller: RideChicagoAutoBundle:Services\Classes:get, _format: json}  
  
classrooms_create:
  pattern: /api/classes/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Classes:create, _format: json}    
  methods: [POST]
  
registration_get:
  pattern: /api/registration
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:get, _format: json}  
  
registrations_create:
  pattern: /api/registration/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:create, _format: json}    
  methods: [POST]
  
registrations_get:
  pattern: /api/registration
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:get, _format: json}    
  
registrations_get_from_classroom:
  pattern: /api/registration/getfromclassroom/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:getFromClassroom, _format: json}    
  requirements:
    id: \d+
  
# Security Routes
  
login_path:
  pattern: /admin/login
login_check_path:
  pattern: /admin/login_check
  methods:  [POST]
logout_path:
  pattern: /admin/logout