ride_chicago_auto_homepage:
    pattern:  /
    defaults: { _controller: RideChicagoAutoBundle:Default:index }
    
auto_admin_index:
    pattern:  /admin/
    defaults: { _controller: RideChicagoAutoBundle:Admin\Index:index }
    
auto_admin_login:
    pattern:  /login
    defaults: { _controller: RideChicagoAutoBundle:Admin\Login:index }
    
auto_admin_users_view:
    pattern:  /admin/users
    defaults: { _controller: RideChicagoAutoBundle:Admin\Users\ViewUsers:index }    
    
auto_admin_users_add:
    pattern:  /admin/users/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Users\AddUser:index }  
    
auto_admin_classes_view:
    pattern:  /admin/classes
    defaults: { _controller: RideChicagoAutoBundle:Admin\Classes\ClassSchedules:index }
        
auto_admin_classes_add:
    pattern:  /admin/classes/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Classes\AddClass:index }
        
auto_admin_classestypes_view:
    pattern:  /admin/class-types
    defaults: { _controller: RideChicagoAutoBundle:Admin\Classes\ClassTypes:index }
        
auto_admin_classestypes_add:
    pattern:  /admin/class-types/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Classes\AddClassType:index }
    
# API routes    

navigation:
  pattern: /api/navigation
  defaults: {_controller: RideChicagoAutoBundle:Services\Navigation:index, _format: json}
  
users_get:
  pattern: /api/users
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json} 
  
users_create:
  pattern: /api/users/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:create, _format: json}    
  methods: [POST]  
  
users_delete:
  pattern: /api/users/delete
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:delete, _format: json}    
  methods: [POST]
  
classtypes_get:
  pattern: /api/class-types
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:get, _format: json}  
  
class_sch_get:
  pattern: /api/classes
  defaults: {_controller: RideChicagoAutoBundle:Services\Classes:get, _format: json}  
  
# Security Routes
  
login_path:
  pattern: /admin/login
login_check_path:
  pattern: /admin/login_check
  methods:  [POST]
logout_path:
  pattern: /admin/logout