ride_chicago_auto_homepage:
    pattern:  /
    defaults: { _controller: RideChicagoAutoBundle:Default:index }
    
auto_admin_index:
    pattern:  /admin
    defaults: { _controller: RideChicagoAutoBundle:Admin\Index:index }
    
auto_admin_login:
    pattern:  /login
    defaults: { _controller: RideChicagoAutoBundle:Admin\Login:index }
    
auto_admin_users_view:
    pattern:  /admin/users
    defaults: { _controller: RideChicagoAutoBundle:Admin\Users\ViewUsers:index }    
    
auto_admin_users_add:
    pattern:  /admin/users/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Users\AddUser:index }
    
# API routes    

navigation:
  pattern: /api/navigation
  defaults: {_controller: RideChicagoAutoBundle:Services\Navigation:index, _format: json}
  
users_get:
  pattern: /api/users
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json}  
  
# Security Routes
  
login_path:
  pattern: /admin/login
login_check_path:
  pattern: /admin/login_check
  methods:  [POST]
logout_path:
  pattern: /admin/logout