ride_chicago_auto_homepage:
    pattern:  /
    defaults: { _controller: RideChicagoAutoBundle:Default:index }
    
rca_classes:
    pattern:  /classes
    defaults: { _controller: RideChicagoAutoBundle:Default:classes }
 
rca_schedule:
    pattern:  /schedule
    defaults: { _controller: RideChicagoAutoBundle:Default:schedule }

rca_permits:
    pattern:  /permits
    defaults: { _controller: RideChicagoAutoBundle:Default:permits }

 
rca_pricing:
    pattern:  /pricing
    defaults: { _controller: RideChicagoAutoBundle:Default:pricing }

rca_faq:
    pattern:  /faq
    defaults: { _controller: RideChicagoAutoBundle:Default:faq }

rca_contact:
    pattern:  /contact
    defaults: { _controller: RideChicagoAutoBundle:Default:contact }

 
    
auto_admin_index:
    pattern:  /admin/
    defaults: { _controller: RideChicagoAutoBundle:Admin\Index:index }
    
auto_admin_login:
    pattern:  /login
    defaults: { _controller: RideChicagoAutoBundle:Admin\Login:index }
    
auto_admin_users_view:
    pattern:  /admin/users
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userView }
    
auto_admin_users_add:
    pattern:  /admin/users/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userAdd }  
        
auto_admin_users_update:
    pattern:  /admin/users/edit/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:userUpdate }  
    
auto_admin_classes_view:
    pattern:  /admin/classes
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classView }
        
auto_admin_classes_add:
    pattern:  /admin/classes/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classAdd }
        
auto_admin_classestypes_view:
    pattern:  /admin/class-types
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesView }
        
auto_admin_classestypes_add:
    pattern:  /admin/class-types/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesAdd }
         
auto_admin_classestypes_update:
    pattern:  /admin/class-types/edit/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:classTypesEdit }
    
auto_admin_registration:
    pattern:  /admin/registration
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationView }   
    
auto_admin_registration_add:
    pattern:  /admin/registration/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationAdd }
    
auto_admin_registration_add_existing:
    pattern:  /admin/registration/add-existing
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationAddExisting }
    
auto_admin_registration_update:
    pattern:  /admin/registration/update/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:registrationUpdate }
    requirements:
        id: \d+
        
auto_admin_lesson_add:
    pattern: /admin/lesson/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonAdd }
            
auto_admin_lesson_add_existing:
    pattern: /admin/lesson/add-existing
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonAddExisting }
    
auto_admin_lesson_update:
    pattern: /admin/lesson/update/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonUpdate }
    requirements:
        id: \d+
    
auto_admin_lesson_view:
    pattern: /admin/lesson
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonView }
    
auto_admin_lessonrate_add:
    pattern: /admin/lessonrate/add
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonRateAdd }
   
auto_admin_lessonrate_update:
    pattern: /admin/lessonrate/update/{id}
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonRateUpdate }
    requirements:
        id: \d+
    
auto_admin_lessonrate_view:
    pattern: /admin/lessonrate
    defaults: { _controller: RideChicagoAutoBundle:Admin\Template:lessonRateView }


# API routes    

navigation:
  pattern: /api/navigation
  defaults: {_controller: RideChicagoAutoBundle:Services\Navigation:index, _format: json}
  
users_get:
  pattern: /api/users
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json} 
    
users_get_single:
  pattern: /api/users/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:get, _format: json} 
  requirements:
    id: \d+
  
users_create:
  pattern: /api/users/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:create, _format: json}    
  methods: [POST]  
  
users_update:
  pattern: /api/users/update
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:update, _format: json}    
  methods: [POST]  
  
users_delete:
  pattern: /api/users/delete
  defaults: {_controller: RideChicagoAutoBundle:Services\Users:delete, _format: json}    
  methods: [POST]
  
classtypes_get:
  pattern: /api/class-types
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:get, _format: json}    
  
classtypes_get_single:
  pattern: /api/class-types/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:get, _format: json}    
  requirements:
    id: \d+
  
classtypes_reorder:
  pattern: /api/class-types/reorder
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:reorder, _format: json}    
  methods: [POST]  
  
classtypes_create:
  pattern: /api/class-types/create
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:create, _format: json}    
  methods: [POST]
  
classtypes_update:
  pattern: /api/class-types/update
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:update, _format: json}    
  methods: [POST]
  
classtypes_delete:
  pattern: /api/class-types/delete
  defaults: {_controller: RideChicagoAutoBundle:Services\ClassTypes:delete, _format: json}    
  methods: [POST]

classrooms_get:
  pattern: /api/classes
  defaults: {_controller: RideChicagoAutoBundle:Services\Classes:get, _format: json}  
  
classrooms_create:
  pattern: /api/classes/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Classes:create, _format: json}    
  methods: [POST]
  
registration_get:
  pattern: /api/registration
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:get, _format: json}  
  
registrations_create:
  pattern: /api/registration/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:create, _format: json}    
  methods: [POST]
  
registrations_createFromExistingStudent:
  pattern: /api/registration/createFromExistingStudent
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:createFromExistingStudent, _format: json}    
  methods: [POST]
  
registrations_get:
  pattern: /api/registration
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:get, _format: json}   
  
registrations_get_single: 
  pattern: /api/registration/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:get, _format: json}   
  requirements:
    id: \d+
    
registrations_get_from_classroom:
  pattern: /api/registration/getfromclassroom/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:getFromClassroom, _format: json}    
  requirements:
    id: \d+
    
registrations_update:
  pattern: /api/registration/update
  defaults: {_controller: RideChicagoAutoBundle:Services\Registration:update, _format: json}    
  methods: [POST]
    
customers_get:
  pattern: /api/customer
  defaults: {_controller: RideChicagoAutoBundle:Services\Customer:get, _format: json}    
  
customers_get_single:
  pattern: /api/customer/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Customer:get, _format: json}    
  requirements:
    id: \d+
    
lessons_get:
  pattern: /api/lesson
  defaults: {_controller: RideChicagoAutoBundle:Services\Lesson:get, _format: json}    
    
lessons_get_single:
  pattern: /api/lesson/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\Lesson:get, _format: json}  
  requirements:
    id: \d+
  
lessons_update:
  pattern: /api/lesson/update
  defaults: {_controller: RideChicagoAutoBundle:Services\Lesson:update, _format: json}    
  methods: [POST]
    
lessons_create:
  pattern: /api/lesson/create
  defaults: {_controller: RideChicagoAutoBundle:Services\Lesson:create, _format: json}    
  methods: [POST]  
  
lessons_createFromExistingStudent:
  pattern: /api/lesson/createFromExistingStudent
  defaults: {_controller: RideChicagoAutoBundle:Services\Lesson:createFromExistingStudent, _format: json}    
  methods: [POST]
    
lessonrates_get:
  pattern: /api/lessonrate
  defaults: {_controller: RideChicagoAutoBundle:Services\LessonRate:get, _format: json}  
  
lessonrates_get_single:
  pattern: /api/lessonrate/{id}
  defaults: {_controller: RideChicagoAutoBundle:Services\LessonRate:get, _format: json}   
  requirements:
    id: \d+
  
lessonrates_update:
  pattern: /api/lessonrate/update
  defaults: {_controller: RideChicagoAutoBundle:Services\LessonRate:update, _format: json}    
  methods: [POST]
    
lessonrates_create:
  pattern: /api/lessonrate/create
  defaults: {_controller: RideChicagoAutoBundle:Services\LessonRate:create, _format: json}    
  methods: [POST]
    
  
# Security Routes
  
login_path:
  pattern: /admin/login
login_check_path:
  pattern: /admin/login_check
  methods:  [POST]
logout_path:
  pattern: /admin/logout