parameters:
#    ride_chicago_auto.example.class: RideChicago\AutoBundle\Example

services:
#    ride_chicago_auto.example:
#        class: %ride_chicago_auto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    authentication_handler:
        class: RideChicago\AutoBundle\Handler\AuthenticationHandler
        
    applogger:
      class: Monolog\Logger
      arguments: [logdata]
      calls:
        - [pushHandler, [@applogger_handler]]
        
    applogger_handler:
      class: Monolog\Handler\StreamHandler
      arguments: [%kernel.logs_dir%/ride-chicago.log, 100]