parameters:
#    ride_chicago_auto.example.class: RideChicago\AutoBundle\Example

services:
#    ride_chicago_auto.example:
#        class: %ride_chicago_auto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    authentication_handler:
        class: RideChicago\AutoBundle\Handler\AuthenticationHandler
