<?php

namespace RideChicago\AutoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {
	/**
	 * @return type
	 */
	public function findAllOrderByLastName() {
		$query = $this->getEntityManager()
			->createQuery('
				SELECT c, p FROM RideChicagoAutoBundle:Customer c
				JOIN c.profile p
				ORDER BY p.last_name ASC
			');
		try { 
			return $query->getResult();
		} catch (NoResultException $e) {
			return null;
		}
	}
}
